TRUNCATE TABLE `roles`;
TRUNCATE TABLE `permissions`;
TRUNCATE TABLE `auths`;
TRUNCATE TABLE `tenants`;
TRUNCATE TABLE `auth_tenants`;
TRUNCATE TABLE `model_permissions`;

INSERT INTO `roles` (id, name) VALUES
(1, 'Superadmin'), (2, 'Admin');


INSERT INTO `permissions` ( name, id) VALUES
('Crear Rol',1),
('Asignar Permiso a Rol', 2),
('Crear Permisos', (UUID())),
('Asignar Rol a Usuario', (UUID())),
('Asignar Permiso a Usuario', (UUID())),
('Obtener Firma Cloudinary', (UUID())),
('Verificar Usuario', (UUID())),
('Ver Usuarios', (UUID())),
('Crear Usuario', (UUID())),
('Editar Usuario', (UUID())),
('Eliminar Usuario', (UUID())),
('Crear Base de Datos', (UUID())),
('Asignar Base de Datos', (UUID())),
('Obtener Base de Datos', (UUID())),
('Crear Inquilinos', (UUID())),
('Ver Inquilinos', (UUID())),
('Modificar Inquilinos', (UUID())),
('Ver Imágenes', (UUID())),
('Crear Imágenes', (UUID())),
('Eliminar Imágenes', (UUID())),
('Guardar Preferencia', (UUID())),
('Obtener Preferencia', (UUID())),
('Crear Clientes', (UUID())),
('Ver Clientes', (UUID())),
('Editar Clientes', (UUID())),
('Eliminar Clientes', (UUID())),
('Confirmar Préstamo', (UUID())),
('Reestructurar Préstamo', (UUID())),
('Crear Préstamos', (UUID())),
('Editar Préstamos', (UUID())),
('Eliminar Préstamos', (UUID())),
('Ver Préstamos', (UUID())),
('Aprobar Préstamos', (UUID())),
('Rechazar Préstamos', (UUID())),
('Crear Contactos', (UUID())),
('Asignar Contactos', (UUID())),
('Ver Contactos', (UUID())),
('Editar Contactos', (UUID())),
('Eliminar Contactos', (UUID())),
('Crear Datos Laborales', (UUID())),
('Editar Datos Laborales', (UUID())),
('Eliminar Datos Laborales', (UUID())),
('Ver Datos Laborales', (UUID())),
('Crear Documentos', (UUID())),
('Ver Documentos', (UUID())),
('Editar Documentos', (UUID())),
('Eliminar Documentos', (UUID())),
('Ver Reportes de Clientes', (UUID())),
('Enviar Mensajes', (UUID())),
('Ver Mensajes', (UUID())),
('Conectarse a WhatsApp', (UUID())),
('Desconectarse de WhatsApp', (UUID())),
('Crear Amortizaciones', (UUID())),
('Ver Amortizaciones', (UUID())),
('Editar Amortizaciones', (UUID())),
('Eliminar Amortizaciones', (UUID())),
('Crear Abogados', (UUID())),
('Ver Abogados', (UUID())),
('Editar Abogados', (UUID())),
('Eliminar Abogados', (UUID())),
('Asignar Abogado a Préstamos', (UUID())),
('Asignar Abogado a Pagos', (UUID())),
('Generar Contrato', (UUID())),
('Asignar Condiciones de Morosidad', (UUID())),
('Registrar Garantías', (UUID())),
('Ver Reportes de Préstamos', (UUID())),
('Crear Pagos', (UUID())),
('Ver Pagos', (UUID())),
('Editar Pagos', (UUID())),
('Eliminar Pagos', (UUID())),
('Ver Reportes de Pagos', (UUID())),
('Personalizar Pagos', (UUID())),
('Establecer Honorarios de Abogado', (UUID())),
('Crear Gastos', (UUID())),
('Ver Gastos', (UUID())),
('Editar Gastos', (UUID())),
('Eliminar Gastos', (UUID())),
('Crear Condiciones', (UUID())),
('Ver Condiciones', (UUID())),
('Editar Condiciones', (UUID())),
('Eliminar Condiciones', (UUID())),
('Crear Redes Sociales', (UUID())),
('Ver Redes Sociales', (UUID())),
('Editar Redes Sociales', (UUID())),
('Eliminar Redes Sociales', (UUID())),
('Crear Información', (UUID())),
('Ver Información', (UUID())),
('Editar Información', (UUID())),
('Eliminar Información', (UUID())),
('Crear Moras', (UUID())),
('Ver Mora', (UUID())),
('Editar Mora', (UUID())),
('Eliminar Mora', (UUID())),
('Ver Reportes de Gastos', (UUID())),
('Crear Métodos de Pago', (UUID())),
('Ver Métodos de Pago', (UUID())),
('Editar Métodos de Pago', (UUID())),
('Ver Papelera', (UUID())),
('Restaurar Datos', (UUID())),
('Eliminar Métodos de Pago', (UUID()));

INSERT INTO `auths` (id, email, password, username, name, lastname, verifiedAt, infoId)
VALUES
(1, 'developer@ismaelcm.dev','$2a$12$5ZdhDxFotW64vqX.KAqoeuBN.0DTt9SXwJpqJwJzRbPY.veNXghkG', 'icontreras','Ismael','Contreras', '2024-01-01 12:00:01', 1),
(2,'user1@example.com', '$2a$10$sOhAGjEUAIGVSVffACk3POMbIzkDorKX3imNeCFndiJQMCx7elimK', 'user1', "User","One", '2024-01-01 12:00:01',NULL);

INSERT INTO `tenants` (name, `key`) VALUES ('Base de Datos Administrador','sigpres_main_tenant');

INSERT INTO `auth_roles` (authId, roleId) VALUES (1,1);

INSERT INTO `model_permissions` (permissionId, modelId, modelType) VALUES (1,1, 'auth'),(2,1, 'auth');