enum PermissionEnums {
  createRole = "Crear Rol",
  getCloudinarySign = "Obtener Firma Cloudinary",
  createPermission = "Crear Permisos",
  asignRoleToUser = "Asignar Rol a Usuario",
  asignPermissionToUser = "Asignar Permiso a Usuario",
  asignPermissionToRole = "Asignar Permiso a Rol",
  verifyUser = "Verificar Usuario",
  createDatabase = "Crear Base de Datos",
  assignDatabase = "Asignar Base de Datos",
  getDatabase = "Obtener Base de Datos",
  createTenant = "Crear Inquilinos",
  getTenant = "Ver Inquilinos",
  editTenant = "Modificar Inquilinos",
  openCashier = "Abrir Caja",
  getImages = "Ver Imágenes",
  createImages = "Crear Imágenes",
  deleteImages = "Eliminar Imágenes",
  setPreference = "Guardar Preferencia",
  getPreference = "Obtener Preferencia",
  createClients = "Crear Clientes",
  getClients = "Ver Clientes",
  editClients = "Editar Clientes",
  deleteClients = "Eliminar Clientes",
}

export default PermissionEnums;
